apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unsri-backend

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - auth-service.yaml
  - attendance-service.yaml
  - api-gateway.yaml

