apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: unsri-backend
type: Opaque
stringData:
  password: unsri_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: unsri-backend
type: Opaque
stringData:
  secret: your-secret-key-change-in-production

